version: "3.9"  # optional since v1.27.0

services:
  api:
    image: registry.local:5000/eitaa-api:latest
    build: .
    ports:
      - 8082:80
    env_file:
      - .env.example
    depends_on: 
      - db
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - broker-data:/data
  
  redis:
    image: redis:6.0.9-alpine
    volumes:
      - redis-data:/data

  worker:
    image: registry.ds:5000/worker:latest
    build: .
    command: celery -A worker.celery worker --hostname w@%h --loglevel=info
    env_file:
      - .env.example
    depends_on:
      - rabbitmq
      - db
      - redis

  beat:
    image: registry.ds:5000/worker:latest
    build: .
    command: celery -A worker.celery beat -S redbeat.RedBeatScheduler --max-interval 10 --loglevel=debug 
    env_file:
      - .env.example
    depends_on:
      - rabbitmq
      - db
      - redis

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@db:27017/
    depends_on: 
      - db

volumes:
  mongo-data:
  broker-data:
  redis-data:
